name: Scully Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cmgriffing/scully-gh-pages-action@v11
        with:
          access-token: ${{ secrets.DEPLOY_PAT }}
          deploy-branch: gh-pages
