name: Scully Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cmgriffing/scully-gh-pages-action@v9
        with:
          access-token: ${{ secrets.DEPLOY_PAT }}
          deploy-branch: gh-pages
          build-args: --base-href /riethmue.github.io/
